// Generated by CoffeeScript 1.6.3
var HandlebarsCompiler, handlebars, sysPath, umd;

handlebars = require('handlebars');

umd = require('umd-wrapper');

sysPath = require('path');

module.exports = HandlebarsCompiler = (function() {
  HandlebarsCompiler.prototype.brunchPlugin = true;

  HandlebarsCompiler.prototype.type = 'template';

  HandlebarsCompiler.prototype.extension = 'hbs';

  HandlebarsCompiler.prototype.pattern = /\.(?:hbs|handlebars)$/;

  function HandlebarsCompiler(config) {
    this.config = config;
    null;
  }

  HandlebarsCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result;
    try {
      return result = umd("Handlebars.template(" + (handlebars.precompile(data)) + ")");
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  HandlebarsCompiler.prototype.include = [sysPath.join(__dirname, '..', 'vendor', 'handlebars.runtime-1.0.js')];

  return HandlebarsCompiler;

})();
